"""
Nepali register classifier: spoken · newspaper · translationese.

Why three and not two. Nepali writing and Nepali speech are far apart —
newspapers run on passive nominalisation (गरिएको छ, जनाइएको छ) and Sanskritic
vocabulary (उक्त, बमोजिम, सम्बन्धमा) that nobody uses out loud. A voice bot
needs the OPPOSITE register from the corpus it is trained and grounded on:
newspaper Nepali goes IN (RAG, pretraining), spoken Nepali must come OUT.

The third class is the one that actually costs money. "Translationese" is
Nepali generated by thinking in English and substituting words — grammatical,
Devanagari, and instantly recognisable as not-a-person. Its signature is
structural, not lexical:

  * pro-drop violation — Nepali drops subjects; English calques keep म and
    तपाईं in every clause
  * light-verb calques — प्रदान गर्नु for "provide", प्राप्त गर्नु for
    "retrieve", where Nepali says दिनु and लिनु
  * no sentence-final particles — real speech carries नि, त, है, पो, क्यारे
  * English discourse scaffolding rendered literally — "यो एउटा राम्रो प्रश्न हो"

Scoring is evidence-based: each marker names itself so a failure can be read,
not just counted.
"""
import re

from himalaya_support.adapt.honorific import check_honorific

TOKEN = re.compile(r'[ऀ-ॣ०-९ॱ-ॿ]+|[A-Za-z]+')
WORD_TOKEN = re.compile(r'[A-Za-z]+|[ऀ-ॿ]+')
LIST_MARKER = re.compile(r'(?m)^\s*(?:\d+[.)]|[१-९००-९]+[.)]|[-•])\s+')
MARKDOWN = re.compile(r'(?:```?|\*\*?|__?|^\s*#+\s+)', re.MULTILINE)

# ---------------------------------------------------------------- newspaper
NEWSPAPER = {
    "गरिएको": 3.0, "भइरहेको": 2.0, "जनाइएको": 3.5, "गरिएका": 3.0, "भएको": 1.5,
    "उक्त": 3.5, "तत्पश्चात": 3.5, "बमोजिम": 3.5, "सम्बन्धमा": 3.0, "सम्बन्धी": 2.5,
    "अनुसार": 2.0, "प्रति": 1.5, "निकाय": 2.5, "सार्वजनिक": 2.0, "कार्यान्वयन": 2.5,
    "प्राधिकरण": 2.5, "मन्त्रिपरिषद्": 3.0, "प्रतिबद्धता": 2.5, "व्यवस्थापन": 2.0,
    "तयारी": 1.0, "पुष्टि": 2.0, "आर्थिक": 1.5, "नीति": 1.5, "निर्देशन": 2.0,
    "छलफल": 1.5, "प्रक्रिया": 1.5, "सन्दर्भमा": 2.5, "उल्लेख": 2.5, "तथा": 2.5,
}
# passive / reportive construction: the newspaper voice in one pattern
NEWS_PATTERNS = [
    (re.compile(r"गरिएको\s+छ"), 3.0, "passive गरिएको छ"),
    (re.compile(r"जनाइएको\s+छ"), 3.5, "reportive जनाइएको छ"),
    (re.compile(r"भएको\s+(?:छ|हो)"), 2.0, "nominalised भएको छ/हो"),
    (re.compile(r"का\s+अनुसार"), 2.5, "attribution का अनुसार"),
    (re.compile(r"[०-९]"), 1.0, "Devanagari numerals"),
    (re.compile(r"वि\.?\s?सं\.?"), 2.5, "विक्रम सम्बत् dating"),
]

# ------------------------------------------------------------------- spoken
SPOKEN_PARTICLES = {"नि", "त", "है", "पो", "क्यारे", "अनि", "हैन", "नै", "रे", "कि",
                    "तिमी", "तिमीलाई", "तिम्रो", "अलिकति", "त्यसपछि"}
SPOKEN_PATTERNS = [
    (re.compile(r"(?:भन्नुहोस्|गरौं)"), 2.0, "spoken imperative"),
    (re.compile(r"(?:नि|है|क्यारे|पो|रे)\s*[।?!,]"), 3.0, "sentence-final particle"),
    (re.compile(r"हैन\s*[र?]|हो\s*नि|छैन\s*[र?]|छ\s*[र?]\s*[।?]?"), 3.0, "tag question"),
    (re.compile(r"\b(?:न|नु)\s*[।?!]"), 1.5, "softening imperative"),
    (re.compile(r"अनि\s"), 2.0, "अनि as discourse connector"),
    (re.compile(r"[a-zA-Z]{3,}"), 1.5, "code-mixed English"),
]

# ----------------------------------------------------------- translationese
CALQUES = [
    (re.compile(r"प्रदान\s*गर्"), 3.5, "प्रदान गर्नु calque for 'provide' (Nepali: दिनु)"),
    (re.compile(r"प्राप्त\s*गर्"), 3.0, "प्राप्त गर्नु calque for 'obtain/retrieve' (Nepali: लिनु/पाउनु)"),
    (re.compile(r"यो\s+एउटा(?:\s+\S+){1,3}\s+हो"), 3.5, "'this is a ...' English filler frame"),
    (re.compile(r"म\s+एउटा\s+(?:AI|एआई|कृत्रिम)"), 4.0, "'I am an AI ...' disclosure calque"),
    (re.compile(r"म\s+तपाईंलाई\s+कसरी\s+(?:मद्दत|सहयोग)"), 3.5, "'how can I help you' literal"),
    (re.compile(r"जब\s+म\s"), 2.5, "'while I ...' English subordination"),
    (re.compile(r"के\s+तपाईं\s+कृपया"), 3.0, "'could you please' literal frame"),
    (re.compile(r"के\s+तपाईं\s+कृपया"), 5.0, "formal please calque"),
    (re.compile(r"म\s+यहाँ\s+छु"), 3.0, "'I am here to ...' calque"),
    (re.compile(r"म\s+तपाईंको\s+खाता\s+जाँच"), 4.0, "assistant account-check calque"),
    (re.compile(r"तपाईं\s+कृपया\s+आफ्नो"), 4.0, "formal please frame"),
    (re.compile(r"म\s+यहाँ\s+तपाईंलाई\s+सहयोग"), 4.0, "assistant service calque"),
    (re.compile(r"म\s+यो\s+अनुरोध\s+प्रक्रिया"), 4.0, "process request calque"),
    (re.compile(r"म\s+तपाईंको\s+समस्या\s+समाधान"), 4.0, "assistant solution calque"),
    (re.compile(r"म\s+तपाईंको\s+सेवाका\s+लागि"), 4.0, "service disclosure calque"),
    (re.compile(r"म\s+यहाँ\s+तपाईंको\s+सेवाका\s+लागि\s+छु"), 5.0, "service disclosure frame"),
    (re.compile(r"कुनै\s+पनि\s+प्रश्न\s+भए"), 2.0, "'if you have any questions' boilerplate"),
]


def _sentences(text: str) -> list[str]:
    return [s for s in re.split(r"(?<=[।॥.!?])\s+", text.strip()) if s.strip()]


def classify(text: str) -> dict:
    text = (text or "").strip()
    if not text:
        return {"register": "unknown", "scores": {}, "evidence": []}

    tokens = TOKEN.findall(text)
    news = spoken = trans = 0.0
    evidence: list[str] = []

    for tok in tokens:
        if tok in NEWSPAPER:
            news += NEWSPAPER[tok]
            evidence.append(f"news:{tok}")
        elif tok in SPOKEN_PARTICLES:
            spoken += 1.5
            evidence.append(f"spoken:{tok}")

    for rx, w, label in NEWS_PATTERNS:
        if rx.search(text):
            news += w
            evidence.append(f"news:{label}")
    for rx, w, label in SPOKEN_PATTERNS:
        if rx.search(text):
            spoken += w
            evidence.append(f"spoken:{label}")
    for rx, w, label in CALQUES:
        if rx.search(text):
            trans += w
            evidence.append(f"calque:{label}")

    # Pro-drop violation: Nepali drops subject pronouns. One म/तपाईं per
    # sentence is normal; one in every sentence is English word order in
    # Devanagari clothing.
    sents = _sentences(text)
    pronoun_sents = sum(1 for s in sents if re.search(r"\bम\b|तपाईं", s))
    if len(sents) >= 2 and pronoun_sents == len(sents):
        trans += 2.5
        evidence.append("calque:subject pronoun in every sentence (pro-drop violation)")

    # Speech that carries no particle at all is a weak translationese signal.
    if spoken == 0 and len(tokens) >= 8 and news < 2.0:
        trans += 1.0
        evidence.append("calque:no sentence-final particle in conversational text")

    total = news + spoken + trans
    if total < 1.5:
        return {"register": "unknown", "scores": {"newspaper": news, "spoken": spoken,
                                                  "translationese": trans},
                "evidence": evidence, "strength": round(total, 1)}

    scores = {"newspaper": round(news / total, 3),
              "spoken": round(spoken / total, 3),
              "translationese": round(trans / total, 3)}
    register = max(scores, key=scores.get)
    return {"register": register, "scores": scores, "evidence": evidence,
            "strength": round(total, 1)}


def speakability(text: str, max_seconds: float = 22.0) -> dict:
    """Check whether text can be spoken as one short voice response."""
    text = (text or "").strip()
    words = WORD_TOKEN.findall(text)
    latin_words = [word for word in words if re.fullmatch(r"[A-Za-z]+", word)]
    longest_latin_run = max((len(WORD_TOKEN.findall(run))
                             for run in re.findall(r"(?:[A-Za-z]+\s*)+", text)), default=0)
    list_markers = LIST_MARKER.findall(text)
    problems = []
    if list_markers:
        problems.append("list markers")
    if MARKDOWN.search(text):
        problems.append("markdown")
    if text.count("|") >= 2:
        problems.append("table pipes")
    if len(re.findall(r"[()]", text)) >= 4:
        problems.append("too many parentheticals")
    if text.count('"') + text.count("'") >= 6:
        problems.append("too many quotation marks")
    if longest_latin_run >= 4:
        problems.append("long consecutive English run")
    latin_ratio = len(latin_words) / len(words) if words else 0.0
    if latin_ratio > 0.70:
        problems.append("too much Latin text")
    estimated_seconds = len(re.findall(r"[ऀ-ॿ]", text)) / 15.0
    if estimated_seconds > max_seconds:
        problems.append("too long")
    return {"speakable": not problems, "problems": problems,
            "estimated_seconds": round(estimated_seconds, 3),
            "list_markers": list_markers, "latin_ratio": round(latin_ratio, 3)}


def check_reply(text: str) -> tuple[bool, str]:
    """Gate for assistant output: a voice bot must speak, not write or translate."""
    speech = speakability(text)
    if not speech["speakable"]:
        return False, "unspeakable — " + ", ".join(speech["problems"])
    honorific = check_honorific(text, "high")
    if not honorific["ok"]:
        return False, "honorific — " + honorific["reason"]
    r = classify(text)
    if r["register"] == "translationese":
        return False, "reads as translated English — " + next(
            (e for e in r["evidence"] if e.startswith("calque:")), "structure")
    if r["register"] == "newspaper":
        return False, "newspaper register — too formal to say out loud"
    return True, r["register"]
